env:
  - GO111MODULE=on
builds:
  - #
    id: build
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - #
    id: default
    builds:
      - build
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      # add only the binary, skipping README and LICENSE
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
