language: go
branches:
  only:
    - master
    - devel
    - /^v/
go_import_path: github.com/squat/terraform-provider-vultr
install:
  - make setup-tools
matrix:
  include:
    - go: 1.10.x
      env:
        - GO111MODULE=off
      script:
        - make build
        - make test
    - go: 1.12.x
      env:
        - GO111MODULE=on
      script:
        - make build
        - make test
