language: go
branches:
  only:
    - master
    - devel
    - /^v/
go_import_path: github.com/squat/terraform-provider-vultr
install:
  - make setup-tools
matrix:
  include:
    - go: 1.10.x
      env:
        - GO111MODULE=off
      script:
        - make build
        - make test
    - go: 1.12.x
      env:
        - GO111MODULE=on
      script:
        - make build
        - make test
# goreleaser does not have a flag to overwrite github release artifacts
# use the travis releases provider to do rolling releases
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/*.txt
    - dist/*.tar.gz
    - dist/*.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: ivandeex/terraform-provider-vultr
    tags: true
    all_branches: true
    go: 1.12.x
    condition: $TRAVIS_PULL_REQUEST == false
